#!/usr/bin/env python3
"""
scaffold_client.py — Auto-generate a complete outreach harness for a new client.

Usage:
    python scaffold_client.py --config client_configs/acme.yaml --dry-run
    python scaffold_client.py --config client_configs/acme.yaml
    python scaffold_client.py --list          # show all onboarded clients

Reads a YAML config and generates:
  1. Complete harness directory (send_emails.py, leads.json, dashboard, templates, docs)
  2. Registers company in company_config.json (Apex orchestrator)
  3. Initializes git repo
  4. Prints next-steps checklist

Requirements: pip install pyyaml
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import textwrap
from datetime import datetime
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML required. Run: pip install pyyaml")
    sys.exit(1)

SCRIPT_DIR = Path(__file__).parent
CONFIG_PATH = SCRIPT_DIR / "company_config.json"
TEMPLATE_DIR = SCRIPT_DIR / "scaffold_templates"


def load_client_config(config_path: str) -> dict:
    with open(config_path) as f:
        return yaml.safe_load(f)


def load_orchestrator_config() -> dict:
    with open(CONFIG_PATH) as f:
        return json.load(f)


def save_orchestrator_config(config: dict) -> None:
    config["last_updated"] = datetime.now().strftime("%Y-%m-%d")
    with open(CONFIG_PATH, "w") as f:
        json.dump(config, f, indent=2)


def validate_config(client: dict, orch: dict) -> list[str]:
    """Validate client config against existing orchestrator state. Returns list of errors."""
    errors = []
    co = client.get("company", {})
    key = co.get("key", "")

    if not key:
        errors.append("company.key is required")
    if key in orch.get("companies", {}):
        errors.append(f"company.key '{key}' already exists in company_config.json")

    segments = client.get("segments", [])
    if not segments:
        errors.append("At least one segment is required")

    for seg in segments:
        seg_id = seg.get("id", "")
        if seg_id in orch.get("segment_registry", {}):
            existing_owner = orch["segment_registry"][seg_id].get("owner", "unknown")
            errors.append(f"Segment {seg_id} already registered (owner: {existing_owner})")
        if not seg.get("template", {}).get("subject"):
            errors.append(f"Segment {seg_id} missing template.subject")
        if not seg.get("template", {}).get("body"):
            errors.append(f"Segment {seg_id} missing template.body")

    harness = client.get("harness", {})
    repo_path = Path(harness.get("repo_path", "").replace("~", str(Path.home())))
    if repo_path.exists() and any(repo_path.iterdir()):
        errors.append(f"Harness path {repo_path} already exists and is not empty")

    return errors


def generate_send_emails(client: dict) -> str:
    """Generate a complete send_emails.py for the client."""
    co = client["company"]
    segments = client["segments"]
    harness = client.get("harness", {})

    # Build SEGMENT_MAP
    seg_map_lines = []
    for seg in segments:
        seg_map_lines.append(f'    "{seg["id"]}": [\n        "{seg["list_name"]}",\n    ],')

    seg_labels_lines = []
    for seg in segments:
        seg_labels_lines.append(f'    "{seg["id"]}": "{seg["name"]}",')

    # Build TEMPLATES dict
    template_lines = []
    for seg in segments:
        tmpl = seg["template"]
        subject = tmpl["subject"]
        body = tmpl["body"].rstrip()
        # Escape for Python string
        body_escaped = body.replace("\\", "\\\\").replace('"', '\\"')
        body_lines = body_escaped.split("\n")
        body_str = '\\n"\n            "'.join(body_lines)
        template_lines.append(
            f'    "{seg["id"]}": {{\n'
            f'        "subject": "{subject}",\n'
            f'        "body": (\n'
            f'            "{body_str}"\n'
            f'        ),\n'
            f'    }},'
        )

    company_name = co["name"]
    brand = co.get("tagline", co["name"])

    return f'''#!/usr/bin/env python3
"""
send_emails.py — Segmented outreach sender for {company_name}
Auto-generated by Apex AI Orchestrator scaffold_client.py

Usage:
    python send_emails.py --segment {segments[0]["id"]}              # live send
    python send_emails.py --segment {segments[0]["id"]} --dry-run    # preview
    python send_emails.py --list-segments              # show all segments and lead counts

IMPORTANT: Always use --dry-run first.
"""

import argparse
import json
import os
import random
import smtplib
import sys
import time
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from dotenv import load_dotenv

load_dotenv()

SCRIPT_DIR     = os.path.dirname(os.path.abspath(__file__))
LEADS_PATH     = os.path.join(SCRIPT_DIR, "leads.json")
EMAIL_LOG_PATH = os.path.join(SCRIPT_DIR, "email_log.json")
SMTP_HOST      = "smtp.gmail.com"
SMTP_PORT      = 465
DELAY_MIN_SEC  = 3 * 60
DELAY_MAX_SEC  = 7 * 60

SEGMENT_MAP: dict[str, list[str]] = {{
{chr(10).join(seg_map_lines)}
}}

SEGMENT_LABELS: dict[str, str] = {{
{chr(10).join(seg_labels_lines)}
}}

LIST_TO_SEGMENT: dict[str, str] = {{
    lst: seg for seg, lists in SEGMENT_MAP.items() for lst in lists
}}

TEMPLATES: dict[str, dict[str, str]] = {{
{chr(10).join(template_lines)}
}}

SENDER_NAME    = os.getenv("SENDER_NAME",     "{co.get('contact', company_name + ' Team')}")
SENDER_EMAIL   = os.getenv("EMAIL_ADDRESS",   "")
SENDER_PHONE   = os.getenv("SENDER_PHONE",    "{co.get('phone', '(555) 123-4567')}")
SENDER_WEBSITE = os.getenv("SENDER_WEBSITE",  "{co.get('website', '')}")
COMPANY_BRAND  = "{company_name}"

DECONFLICT_BATCH = os.path.join(SCRIPT_DIR, ".deconflict_batch.json")


def load_leads() -> list[dict]:
    with open(LEADS_PATH, "r") as f:
        leads = json.load(f)
    if os.path.exists(DECONFLICT_BATCH):
        try:
            with open(DECONFLICT_BATCH) as bf:
                allowed_ids = set(json.load(bf))
            if allowed_ids:
                leads = [l for l in leads if l.get("id") in allowed_ids]
                print(f"  [DECONFLICT] Restricted to {{len(leads)}} leads from orchestrator batch.")
        except (json.JSONDecodeError, KeyError):
            pass
    return leads


def load_log() -> list[dict]:
    if not os.path.exists(EMAIL_LOG_PATH):
        return []
    with open(EMAIL_LOG_PATH, "r") as f:
        return json.load(f)


def save_log(log: list[dict]) -> None:
    with open(EMAIL_LOG_PATH, "w") as f:
        json.dump(log, f, indent=2)


def already_contacted(log: list[dict], email: str) -> bool:
    email = email.lower().strip()
    for entry in log:
        addr = (entry.get("to_email") or entry.get("contact_email") or entry.get("email") or "").lower().strip()
        if addr == email and entry.get("status") in ("sent", "approved"):
            return True
    return False


def compose(lead: dict, segment: str) -> tuple[str, str]:
    tmpl = TEMPLATES[segment]
    merge = {{
        "first_name": lead.get("first_name") or lead.get("contact_name", "there").split()[0],
        "company":    lead.get("company_name", "your organization"),
        "title":      lead.get("title", "your role"),
        "company_brand": COMPANY_BRAND,
        "sender_name": SENDER_NAME,
        "sender_email": SENDER_EMAIL,
        "sender_phone": SENDER_PHONE,
        "sender_website": SENDER_WEBSITE,
    }}
    subject = tmpl["subject"].format(**merge)
    body    = tmpl["body"].format(**merge)
    return subject, body


def build_log_entry(lead: dict, segment: str, subject: str, body: str, status: str) -> dict:
    return {{
        "id":           f"EMAIL-{{lead['id']}}-{{segment}}",
        "lead_id":      lead["id"],
        "segment":      segment,
        "list_name":    lead.get("list_name", ""),
        "contact_name": lead.get("contact_name", ""),
        "first_name":   lead.get("first_name", ""),
        "company_name": lead.get("company_name", ""),
        "title":        lead.get("title", ""),
        "to_email":     lead.get("email", ""),
        "subject":      subject,
        "body":         body,
        "status":       status,
        "sent_at":      datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ") if status == "sent" else None,
        "date_created": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "company":      COMPANY_BRAND,
    }}


def send_via_smtp(email_address: str, app_password: str, to_addr: str, subject: str, body: str) -> None:
    msg = MIMEMultipart()
    msg["From"]    = email_address
    msg["To"]      = to_addr
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))
    with smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) as server:
        server.login(email_address, app_password)
        server.sendmail(email_address, to_addr, msg.as_string())


def cmd_list_segments(leads: list[dict]) -> None:
    log = load_log()
    contacted = {{
        (entry.get("to_email") or "").lower().strip()
        for entry in log
        if entry.get("status") in ("sent", "approved")
    }}
    print("\\n  Segment            Label                              Leads  Remaining")
    print("  " + "\\u2500" * 68)
    total_leads = total_remaining = 0
    for seg_id in sorted(TEMPLATES):
        label    = SEGMENT_LABELS.get(seg_id, "")
        eligible = [
            l for l in leads
            if LIST_TO_SEGMENT.get(l.get("list_name", "")) == seg_id
            and l.get("email", "").strip()
        ]
        remaining = [l for l in eligible if l["email"].lower().strip() not in contacted]
        total_leads     += len(eligible)
        total_remaining += len(remaining)
        print(f"  {{seg_id}}    {{label:<38}} {{len(eligible):>5}}  {{len(remaining):>9}}")
    print("  " + "\\u2500" * 68)
    print(f"  {{'TOTAL':<46}} {{total_leads:>5}}  {{total_remaining:>9}}\\n")


def cmd_send(leads: list[dict], segment: str, dry_run: bool, email_address: str, app_password: str, limit: int | None = None) -> None:
    log = load_log()
    segment_leads = [
        l for l in leads
        if LIST_TO_SEGMENT.get(l.get("list_name", "")) == segment
        and l.get("email", "").strip()
        and not already_contacted(log, l["email"])
    ]
    if limit is not None:
        segment_leads = segment_leads[:limit]

    label = SEGMENT_LABELS.get(segment, segment)
    mode  = "[DRY RUN] " if dry_run else ""

    if not segment_leads:
        print(f"\\n{{mode}}No remaining leads for {{segment}} ({{label}}).")
        return

    print(f"\\n{{mode}}{{segment}} \\u2014 {{label}}")
    print(f"  {{len(segment_leads)}} lead(s) to send\\n")

    sent_count = skipped_count = 0

    for i, lead in enumerate(segment_leads):
        to_addr = lead["email"].strip()
        name    = lead.get("contact_name") or lead.get("first_name", "")
        company = lead.get("company_name", "")
        subject, body = compose(lead, segment)

        print(f"{{'\\u2500' * 62}}")
        print(f"  {{mode}}Send {{i + 1}} of {{len(segment_leads)}}")
        print(f"  To:      {{name}} <{{to_addr}}>")
        print(f"  Company: {{company}}")
        print(f"  Subject: {{subject}}")

        if dry_run:
            print(f"\\n  Body preview:\\n")
            for line in body.split("\\n"):
                print(f"    {{line}}")
            print()
            entry = build_log_entry(lead, segment, subject, body, status="dry-run")
            log.append(entry)
            sent_count += 1
        else:
            try:
                send_via_smtp(email_address, app_password, to_addr, subject, body)
                entry = build_log_entry(lead, segment, subject, body, status="sent")
                log.append(entry)
                save_log(log)
                print(f"  [SENT] \\u2192 {{to_addr}}\\n")
                sent_count += 1
            except smtplib.SMTPAuthenticationError:
                print("  [ERROR] Auth failed. Check EMAIL_ADDRESS and EMAIL_APP_PASSWORD in .env.")
                sys.exit(1)
            except smtplib.SMTPException as exc:
                print(f"  [ERROR] SMTP error: {{exc}} \\u2014 skipping.\\n")
                skipped_count += 1
                continue
            except Exception as exc:
                print(f"  [ERROR] Unexpected error: {{exc}} \\u2014 skipping.\\n")
                skipped_count += 1
                continue

        if i < len(segment_leads) - 1:
            delay = random.randint(DELAY_MIN_SEC, DELAY_MAX_SEC)
            mins, secs = divmod(delay, 60)
            if dry_run:
                print(f"  [DRY RUN] Would wait {{mins}}m {{secs}}s before next send.\\n")
            else:
                print(f"  Waiting {{mins}}m {{secs}}s before next send...\\n")
                time.sleep(delay)

    print(f"{{'\\u2500' * 62}}")
    if dry_run:
        save_log(log)
        print(f"\\n[DRY RUN] Complete. {{sent_count}} email(s) previewed.")
    else:
        print(f"\\nDone. {{sent_count}} sent, {{skipped_count}} skipped.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Segmented outreach sender for {company_name}.",
    )
    parser.add_argument("--segment",       metavar="SEG", help="Segment to send")
    parser.add_argument("--dry-run",       action="store_true", help="Preview without sending")
    parser.add_argument("--list-segments", action="store_true", help="Show all segments")
    parser.add_argument("--limit",         metavar="N", type=int, default=None, help="Cap leads")
    args = parser.parse_args()

    leads = load_leads()

    if args.list_segments:
        cmd_list_segments(leads)
        return

    if not args.segment:
        parser.print_help()
        sys.exit(1)

    segment = args.segment.upper()
    if segment not in TEMPLATES:
        print(f"ERROR: Unknown segment '{{segment}}'. Valid: {{', '.join(sorted(TEMPLATES))}}")
        sys.exit(1)

    email_address = os.getenv("EMAIL_ADDRESS", "")
    app_password  = os.getenv("EMAIL_APP_PASSWORD", "")

    if not args.dry_run and (not email_address or not app_password):
        print("ERROR: EMAIL_ADDRESS and EMAIL_APP_PASSWORD must be set in .env")
        sys.exit(1)

    cmd_send(leads, segment, args.dry_run, email_address, app_password, limit=args.limit)


if __name__ == "__main__":
    main()
'''


def generate_env_example(client: dict) -> str:
    co = client["company"]
    return f"""# {co['name']} Outreach Harness — Environment Variables
# Copy to .env and fill in real values

EMAIL_ADDRESS={co.get('email_account', 'you@company.com')}
EMAIL_APP_PASSWORD=xxxx xxxx xxxx xxxx

SENDER_NAME={co.get('contact', co['name'] + ' Team')}
SENDER_PHONE={co.get('phone', '(555) 123-4567')}
SENDER_WEBSITE={co.get('website', 'www.example.com')}

# Optional — ZeroBounce verification
ZEROBOUNCE_API_KEY=
"""


def generate_agent_learnings(client: dict) -> str:
    co = client["company"]
    segments = client["segments"]
    seg_list = "\n".join(
        f"  - {s['id']}: {s['name']} ({s.get('compliance_hook', 'general')})"
        for s in segments
    )
    other_companies = "DataTech Disposition, ZS Recycling"  # known existing

    return f"""# AGENT_LEARNINGS.md — {co['name']}
# Auto-generated by Apex AI Orchestrator scaffold_client.py
# Last updated: {datetime.now().strftime('%Y-%m-%d')}

## Stack
- Python 3.10+, send_emails.py, Gmail App Password
- Orchestrated by ~/apex-ai-orchestrator/orchestrate.py
- Deconfliction: ~/apex-ai-orchestrator/deconflict.py

## Company Separation — CRITICAL
- This harness is EXCLUSIVELY for {co['name']}
- NEVER mix leads, email accounts, or logs with {other_companies}
- NEVER use another company's Gmail credentials

## Owned Segments
{seg_list}

## Rules
- Always --dry-run before live send
- Respect orchestrator segment ownership
- Log all sends to email_log.json
- 3-7 minute random delay between sends (anti-spam)
- Check ZeroBounce verification status before large sends

## Demo Playbook
1. `python send_emails.py --list-segments`    # Show scope
2. `python send_emails.py --segment {segments[0]['id']} --dry-run --limit 3`  # Preview
3. `python send_emails.py --segment {segments[0]['id']} --limit 5`            # Live send (demo)
"""


def generate_gitignore() -> str:
    return """.env
*.pyc
__pycache__/
node_modules/
.DS_Store
senders.json
venv/
"""


def generate_readme(client: dict) -> str:
    co = client["company"]
    segments = client["segments"]
    harness = client.get("harness", {})

    seg_table = "\n".join(
        f"| {s['id']} | {s['name']} | {s.get('compliance_hook', '-')} |"
        for s in segments
    )

    return f"""# {co['name']} — Outreach Harness

Auto-generated by **Apex AI Orchestrator** for {co['contact']}.

## Segments

| ID | Name | Compliance Hook |
|----|------|-----------------|
{seg_table}

## Quick Start

```bash
# 1. Setup
cp .env.example .env   # Fill in Gmail credentials
pip install python-dotenv

# 2. Import leads
# Add leads to leads.json (see lead format below)

# 3. Preview
python send_emails.py --list-segments
python send_emails.py --segment {segments[0]['id']} --dry-run --limit 3

# 4. Send (via orchestrator)
cd ~/apex-ai-orchestrator
python orchestrate.py --company {co['key']} --segment {segments[0]['id']} --dry-run
python orchestrate.py --company {co['key']} --segment {segments[0]['id']}
```

## Dashboard

```bash
python3 -m http.server {harness.get('dashboard_port', 8082)}
# Open: http://localhost:{harness.get('dashboard_port', 8082)}/demo/dashboard.html
```

## Lead Format (leads.json)

```json
{{
  "id": "LEAD-0001",
  "contact_name": "Jane Doe",
  "first_name": "Jane",
  "last_name": "Doe",
  "title": "IT Director",
  "company_name": "Acme Health",
  "email": "jane@acmehealth.com",
  "email_status": "valid",
  "phone": "",
  "industry": "Healthcare",
  "location": "Los Angeles, CA",
  "list_name": "{segments[0]['list_name']}",
  "source": "manual",
  "date_added": "{datetime.now().strftime('%Y-%m-%d')}",
  "status": "new"
}}
```

## Orchestration

Managed by Apex AI Orchestrator (`~/apex-ai-orchestrator`).
- Segment ownership enforced
- Cross-company dedup active
- All sends logged to master_send_log.json
"""


def generate_tokens(client: dict) -> str:
    co = client["company"]
    tokens = client.get("design_tokens", {})
    colors = tokens.get("colors", {})

    return json.dumps({
        "name": f"{co['name']} Design Tokens",
        "extends": "../descieux-digital/_CONTEXT/DESCIEUX_DIGITAL_TOKENS.json",
        "version": "1.0.0",
        "colors": {
            "accent": {
                "primary": colors.get("primary", "#00C9B1"),
                "secondary": colors.get("secondary", "#2E86DE"),
                "industry": colors.get("accent", "#FF6B35"),
            },
            "neutral": {
                "dark": colors.get("dark", "#0B1929"),
                "card": colors.get("card", "#1A3A5C"),
                "border": "#2a3f5f",
            },
        },
        "typography": {
            "families": {
                "body": tokens.get("font_family", "'Inter', system-ui, sans-serif"),
            },
        },
        "branding": {
            "company-name": co["name"],
            "industry": co.get("industry", ""),
            "tagline": co.get("tagline", ""),
        },
    }, indent=2)


def generate_dashboard(client: dict) -> str:
    """Generate a dark-mode campaign dashboard HTML."""
    co = client["company"]
    segments = client["segments"]
    colors = client.get("design_tokens", {}).get("colors", {})

    primary = colors.get("primary", "#00C9B1")
    secondary = colors.get("secondary", "#2E86DE")
    dark = colors.get("dark", "#0B1929")

    seg_cards = "\n".join(
        f'        <div class="stat-card"><h3>{s["id"]}</h3><p>{s["name"]}</p>'
        f'<span class="count" id="count-{s["id"].lower()}">0</span></div>'
        for s in segments
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{co['name']} — Outreach Dashboard</title>
<link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=DM+Serif+Display&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Inter', sans-serif; background: {dark}; color: #e0e0e0; min-height: 100vh; }}
  .header {{ background: linear-gradient(135deg, {dark}, #1a2a3a); padding: 2rem; border-bottom: 1px solid #2a3f5f; }}
  .header h1 {{ font-family: 'DM Serif Display', serif; font-size: 1.8rem; color: {primary}; }}
  .header p {{ color: #8899aa; margin-top: 0.5rem; font-family: 'DM Mono', monospace; font-size: 0.85rem; }}
  .dashboard {{ padding: 2rem; max-width: 1200px; margin: 0 auto; }}
  .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1.5rem; margin-bottom: 2rem; }}
  .stat-card {{ background: #1a2a3a; border: 1px solid #2a3f5f; border-radius: 12px; padding: 1.5rem; text-align: center; }}
  .stat-card h3 {{ font-family: 'DM Mono', monospace; color: {primary}; font-size: 0.9rem; }}
  .stat-card p {{ color: #8899aa; font-size: 0.8rem; margin: 0.5rem 0; }}
  .stat-card .count {{ font-family: 'DM Serif Display', serif; font-size: 2.5rem; color: #fff; display: block; margin-top: 0.5rem; }}
  .summary-row {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; margin-bottom: 2rem; }}
  .summary-card {{ background: linear-gradient(135deg, {primary}22, {secondary}22); border: 1px solid {primary}44; border-radius: 10px; padding: 1.2rem; text-align: center; }}
  .summary-card .num {{ font-size: 2rem; font-weight: 700; color: {primary}; }}
  .summary-card .label {{ font-size: 0.75rem; color: #8899aa; text-transform: uppercase; letter-spacing: 1px; margin-top: 0.3rem; }}
  .log-table {{ width: 100%; border-collapse: collapse; font-size: 0.85rem; }}
  .log-table th {{ text-align: left; padding: 0.8rem; border-bottom: 2px solid {primary}44; color: {primary}; font-family: 'DM Mono', monospace; }}
  .log-table td {{ padding: 0.8rem; border-bottom: 1px solid #1a2a3a; }}
  .status-sent {{ color: {primary}; }}
  .status-dry {{ color: #f0ad4e; }}
  #last-updated {{ font-family: 'DM Mono', monospace; font-size: 0.75rem; color: #556677; margin-top: 2rem; text-align: center; }}
</style>
</head>
<body>
  <div class="header">
    <h1>{co['name']} Outreach Dashboard</h1>
    <p>Apex AI Orchestrator &mdash; {co.get('industry', 'B2B Outreach')}</p>
  </div>
  <div class="dashboard">
    <div class="summary-row">
      <div class="summary-card"><div class="num" id="total-leads">0</div><div class="label">Total Leads</div></div>
      <div class="summary-card"><div class="num" id="total-sent">0</div><div class="label">Emails Sent</div></div>
      <div class="summary-card"><div class="num" id="total-remaining">0</div><div class="label">Remaining</div></div>
      <div class="summary-card"><div class="num" id="reply-rate">0%</div><div class="label">Reply Rate</div></div>
    </div>
    <h2 style="color:{primary};font-family:'DM Serif Display',serif;margin-bottom:1rem;">Segments</h2>
    <div class="stats-grid">
{seg_cards}
    </div>
    <h2 style="color:{primary};font-family:'DM Serif Display',serif;margin:2rem 0 1rem;">Recent Activity</h2>
    <table class="log-table">
      <thead><tr><th>Date</th><th>Segment</th><th>Contact</th><th>Company</th><th>Status</th></tr></thead>
      <tbody id="log-body"></tbody>
    </table>
    <div id="last-updated"></div>
  </div>
  <script>
    async function loadData() {{
      try {{
        const [leadsRes, logRes] = await Promise.all([
          fetch('../leads.json').catch(() => ({{ json: () => [] }})),
          fetch('../email_log.json').catch(() => ({{ json: () => [] }})),
        ]);
        const leads = await leadsRes.json();
        const log = await logRes.json();
        const sent = log.filter(e => e.status === 'sent');
        document.getElementById('total-leads').textContent = leads.length;
        document.getElementById('total-sent').textContent = sent.length;
        document.getElementById('total-remaining').textContent = Math.max(0, leads.length - sent.length);
        document.getElementById('reply-rate').textContent = sent.length > 0
          ? (sent.filter(e => e.replied_at).length / sent.length * 100).toFixed(1) + '%' : '0%';
        const tbody = document.getElementById('log-body');
        tbody.innerHTML = log.slice(-20).reverse().map(e =>
          `<tr><td>${{e.date_created||''}}</td><td>${{e.segment||''}}</td><td>${{e.contact_name||''}}</td><td>${{e.company_name||''}}</td><td class="${{e.status==='sent'?'status-sent':'status-dry'}}">${{e.status||''}}</td></tr>`
        ).join('');
        document.getElementById('last-updated').textContent = 'Last updated: ' + new Date().toLocaleString();
      }} catch(err) {{ console.error('Dashboard load error:', err); }}
    }}
    loadData();
    setInterval(loadData, 30000);
  </script>
</body>
</html>"""


def generate_requirements() -> str:
    return "python-dotenv>=1.0.0\n"


def generate_init_sh(client: dict) -> str:
    co = client["company"]
    return f"""#!/bin/bash
# {co['name']} Harness — Quick Setup
set -e
echo "Setting up {co['name']} outreach harness..."
python3 -m venv venv 2>/dev/null || true
source venv/bin/activate 2>/dev/null || true
pip install -r requirements.txt -q
if [ ! -f .env ]; then
    cp .env.example .env
    echo "Created .env from template — fill in your Gmail credentials."
fi
echo "Setup complete. Run: python send_emails.py --list-segments"
"""


def scaffold(client: dict, dry_run: bool = False) -> None:
    """Generate the complete harness directory and register in orchestrator."""
    co = client["company"]
    harness = client.get("harness", {})
    segments = client["segments"]
    repo_path = Path(harness.get("repo_path", f"~/{co['key']}-outreach-harness").replace("~", str(Path.home())))

    print(f"\n{'='*62}")
    print(f"  APEX AI ORCHESTRATOR — Client Scaffold")
    print(f"  Company : {co['name']}")
    print(f"  Key     : {co['key']}")
    print(f"  Path    : {repo_path}")
    print(f"  Segments: {', '.join(s['id'] for s in segments)}")
    print(f"  Mode    : {'DRY RUN' if dry_run else 'LIVE'}")
    print(f"{'='*62}\n")

    # Validate
    orch = load_orchestrator_config()
    errors = validate_config(client, orch)
    if errors:
        print("[ERRORS] Cannot proceed:")
        for e in errors:
            print(f"  - {e}")
        sys.exit(1)

    if dry_run:
        print("[DRY RUN] Would create the following structure:\n")
        dirs = [
            repo_path,
            repo_path / "templates",
            repo_path / "docs",
            repo_path / "demo",
            repo_path / "data",
            repo_path / "data" / "certificates",
            repo_path / "leads",
            repo_path / "_CONTEXT",
        ]
        if harness.get("copy_industry_modules", False):
            dirs.append(repo_path / "industry")

        for d in dirs:
            print(f"  [DIR]  {d}")
        files = [
            "send_emails.py", "leads.json", "email_log.json",
            ".env.example", ".gitignore", "README.md",
            "AGENT_LEARNINGS.md", "requirements.txt", "init.sh",
            ".deconflict_batch.json",
            "demo/dashboard.html",
            "_CONTEXT/tokens.json",
        ]
        for s in segments:
            files.append(f"templates/{s['id'].lower()}.txt")
        for f in files:
            print(f"  [FILE] {repo_path / f}")

        print(f"\n  [REGISTER] company_config.json -> {co['key']}")
        for s in segments:
            print(f"  [REGISTER] segment_registry -> {s['id']}: {s['name']}")
        print(f"\n[DRY RUN] No files written. Remove --dry-run to execute.\n")
        return

    # Create directories
    dirs = [
        repo_path,
        repo_path / "templates",
        repo_path / "docs",
        repo_path / "demo",
        repo_path / "data",
        repo_path / "data" / "certificates",
        repo_path / "leads",
        repo_path / "_CONTEXT",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
        print(f"  [DIR]  {d}")

    # Copy industry modules if requested
    if harness.get("copy_industry_modules", False):
        src_industry = SCRIPT_DIR / "industry" if (SCRIPT_DIR / "industry").exists() else Path.home() / "james-outreach-harness" / "industry"
        if src_industry.exists():
            dest_industry = repo_path / "industry"
            if not dest_industry.exists():
                shutil.copytree(src_industry, dest_industry)
                print(f"  [COPY] industry/ <- {src_industry}")

    # Generate files
    files_to_write = {
        "send_emails.py": generate_send_emails(client),
        "leads.json": "[]",
        "email_log.json": "[]",
        ".env.example": generate_env_example(client),
        ".gitignore": generate_gitignore(),
        "README.md": generate_readme(client),
        "AGENT_LEARNINGS.md": generate_agent_learnings(client),
        "requirements.txt": generate_requirements(),
        "init.sh": generate_init_sh(client),
        ".deconflict_batch.json": "[]",
        "demo/dashboard.html": generate_dashboard(client),
        "_CONTEXT/tokens.json": generate_tokens(client),
    }

    # Write template text files
    for seg in segments:
        tmpl = seg.get("template", {})
        content = f"Subject: {tmpl.get('subject', '')}\n\n{tmpl.get('body', '')}"
        files_to_write[f"templates/{seg['id'].lower()}.txt"] = content

    for rel_path, content in files_to_write.items():
        full_path = repo_path / rel_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content)
        print(f"  [FILE] {full_path}")

    # Make init.sh executable
    (repo_path / "init.sh").chmod(0o755)

    # Register in orchestrator
    print(f"\n  Registering in Apex orchestrator...")

    seg_ids = [s["id"] for s in segments]
    seg_names = [s["name"] for s in segments]

    orch["companies"][co["key"]] = {
        "name": co["name"],
        "contact": co.get("contact", "TBD"),
        "email_account": co.get("email_account", "TBD"),
        "repo": harness.get("repo_path", f"~/{co['key']}-outreach-harness"),
        "owned_segments": seg_ids,
        "segment_names": seg_names,
        "status": "setup",
        "notes": f"Auto-scaffolded {datetime.now().strftime('%Y-%m-%d')}. Complete .env setup and lead import before activating.",
    }

    for seg in segments:
        orch["segment_registry"][seg["id"]] = {
            "name": seg["name"],
            "lead_count": 0,
            "owner": co["key"],
        }

    # Update billing if provided
    billing = client.get("billing", {})
    if billing:
        if "client_billing" not in orch:
            orch["client_billing"] = {}
        orch["client_billing"][co["key"]] = {
            "setup_fee": billing.get("setup_fee", 500),
            "monthly_retainer": billing.get("monthly_retainer", 300),
            "status": "pending",
        }

    save_orchestrator_config(orch)
    print(f"  [OK] {co['key']} registered in company_config.json")
    for seg in segments:
        print(f"  [OK] {seg['id']} registered in segment_registry")

    # Init git repo
    try:
        subprocess.run(["git", "init"], cwd=repo_path, capture_output=True)
        subprocess.run(["git", "add", "."], cwd=repo_path, capture_output=True)
        subprocess.run(
            ["git", "commit", "-m", f"Initial scaffold for {co['name']} outreach harness"],
            cwd=repo_path, capture_output=True,
        )
        print(f"  [OK] Git repo initialized with initial commit")
    except Exception:
        print(f"  [WARN] Git init skipped")

    # Print next steps
    print(f"\n{'='*62}")
    print(f"  SCAFFOLD COMPLETE — Next Steps")
    print(f"{'='*62}")
    print(f"""
  1. Fill in credentials:
     cd {repo_path}
     cp .env.example .env
     # Add Gmail App Password

  2. Import leads:
     # Add leads to leads.json (see README.md for format)
     # Or use lead_sourcer.py from apex-ai-orchestrator

  3. Verify leads (optional):
     cd ~/apex-ai-orchestrator
     python lead_verifier.py --file {repo_path}/leads.json

  4. Test:
     python orchestrate.py --company {co['key']} --segment {seg_ids[0]} --dry-run --limit 3

  5. Activate:
     # Update company_config.json: status "setup" -> "active"

  6. Launch:
     python orchestrate.py --company {co['key']} --segment {seg_ids[0]}

  Dashboard: python3 -m http.server {harness.get('dashboard_port', 8082)}
             http://localhost:{harness.get('dashboard_port', 8082)}/demo/dashboard.html
""")


def cmd_list_clients():
    """Show all onboarded clients."""
    orch = load_orchestrator_config()
    print(f"\n{'='*62}")
    print(f"  APEX AI ORCHESTRATOR — All Clients")
    print(f"{'='*62}\n")
    for key, co in orch.get("companies", {}).items():
        icon = {"active": "\u25cf", "setup": "\u25ce", "pending": "\u25cb"}.get(co.get("status", ""), "?")
        print(f"  {icon}  {co['name']:<30} [{co.get('status', 'unknown').upper()}]")
        print(f"       Key     : {key}")
        print(f"       Contact : {co.get('contact', 'TBD')}")
        print(f"       Segments: {', '.join(co.get('owned_segments', []))}")
        print(f"       Repo    : {co.get('repo', 'TBD')}")
        billing = orch.get("client_billing", {}).get(key, orch.get("apex_billing", {}))
        setup = billing.get("setup_fee", billing.get("setup_fee_per_company", "N/A"))
        retainer = billing.get("monthly_retainer", billing.get("monthly_retainer_per_company", "N/A"))
        print(f"       Billing : ${setup} setup + ${retainer}/mo")
        print()

    total = len(orch.get("companies", {}))
    active = sum(1 for c in orch.get("companies", {}).values() if c.get("status") == "active")
    print(f"  Total: {total} clients ({active} active)\n")


def main():
    parser = argparse.ArgumentParser(
        description="Scaffold a complete outreach harness for a new Apex client.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python scaffold_client.py --config client_configs/acme.yaml --dry-run\n"
            "  python scaffold_client.py --config client_configs/acme.yaml\n"
            "  python scaffold_client.py --list\n"
        ),
    )
    parser.add_argument("--config", metavar="YAML", help="Path to client config YAML")
    parser.add_argument("--dry-run", action="store_true", help="Preview without creating files")
    parser.add_argument("--list", action="store_true", help="Show all onboarded clients")
    args = parser.parse_args()

    if args.list:
        cmd_list_clients()
        return

    if not args.config:
        parser.print_help()
        sys.exit(1)

    client = load_client_config(args.config)
    scaffold(client, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
